version: 2
updates:
  - commit-message:
      prefix: chore
    directory: /
    open-pull-requests-limit: 20
    package-ecosystem: npm
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /
    package-ecosystem: docker
    schedule:
      interval: monthly
      day: saturday
  - commit-message:
      prefix: chore
    directory: /tests/e2e_tests
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: monthly
      day: saturday
